### PR TITLE
feat(deps): bump `iam-contracts` and `ethers` version to latest

### PR DESCRIPTION
**Pull request by Harasz**
Revert #170

### CODE REVIEW

**Comment by Harasz** [comment]
Waiting for release of https://github.com/energywebfoundation/passport-did-auth/pull/113

**Review by jrhender — APPROVED** [review]

**Review by jrhender — CHANGES_REQUESTED** [review]
The passport-did-auth is failing when I run locally. I think it might be due to https://energyweb.atlassian.net/browse/ICL-105

**Comment by Harasz** [comment]
Waiting for release of https://github.com/energywebfoundation/passport-did-auth/pull/128

**Review by jrhender — APPROVED** [review]
Third time's the charm!

**Pull request merged**
