### PR TITLE
docs: add list with breaking changes

### PR DESCRIPTION
**Pull request by Harasz**

### CODE REVIEW

**Comment by Harasz** [comment]
image
View of the compiled file.

**Comment by JGiter** [comment]
I suggest to call this `Migration Guide` and put in the docs. This is the way how it is done in `ethers`

**Comment by Harasz** [comment]
It should be added docs folder, but one thing concerns me: `docs` dir is auto generated, so It would be better to add it to root dir and then copy during generation to `docs` dir. What you think? @JGiter @jrhender

**Comment by jrhender** [comment]
@Harasz I thought that only the `api` dir in the `docs` dir is autogenerated. I think the rest is static. Is this not right?

**Comment by Harasz** [comment]
Ohh yeah, you're right. I will move to docs and change to migration guide. Thanks  guys!

**Review by jrhender — APPROVED** [review]

**Pull request merged**
