### PR TITLE
feat/ICS-54 adds versioning to cache server

### PR DESCRIPTION
**Pull request by ahmedolaibrahim**
- Adds versioning to cache server

### CODE REVIEW

**Review by Harasz — COMMENTED** [review]
Why did you remove `package-lock.json`?
What about version of `DIDController`?

**Comment by ahmedolaibrahim** [comment]
> Why did you remove `package-lock.json`

It's not removed, there was some changes  generated based on the `npm install` i did after pulling latest changes.

> What about version of `DIDController`?

I added versioning for DIDController. can you please check again?

**Review by Harasz — APPROVED** [review]

**Review by jrhender — APPROVED** [review]
Looks good to me

**Review by JGiter — APPROVED** [review]

**Review by JGiter — CHANGES_REQUESTED** [review]
I think you also need to change url used by login strategy

**Comment by jrhender** [comment]
> I think you also need to change url used by login strategy

@JGiter I think #165 has accomplished this

**Pull request merged**
