### PR TITLE
Removes claimsIssuer from Claims

### PR DESCRIPTION
**Pull request by ahmedolaibrahim**
- [ ] Remove claimsIssuer from Claims

### CODE REVIEW

**Review by hrachocode — APPROVED** [review]

**Review by jrhender — APPROVED** [review]
Looks good to me 👍

**Comment by jrhender** [comment]
@ahmedolaibrahim did you make changes since my first approval?

**Comment by ahmedolaibrahim** [comment]
> @ahmedolaibrahim did you make changes since my first approval?

No I haven't made any changes

**Review by jrhender — APPROVED** [review]

**Review by jrhender — COMMENTED** [review]
Will this break consumers of cache-server? I don't think so because the API isn't changing, right?

**Pull request merged**
